### ISSUE TITLE
Holy Ghost vs. Holy Spirit

### ISSUE THREAD

**Issue by truthsword** [deeproots/books#15]
I've noticed that in some of the books I've edited, the term "Holy Ghost" appearing in the original (pdf) appears as "Holy Spirit" in the OCR'd text file. Taking a cue from that, I've substituted (Find/Replace) "Holy Spirit" for "Holy Ghost" in the texts I am editing.

Is this substitution desired? Or should we retain the usage from the original text (pdf)?

**Comment by lukewil** [comment]
I'm open to opinions and suggestions. I think I probably added that early on in the process as a search and replace. In some ways its a leftover bit that shows how the project has progressed.

It's certainly an archaic form, and since I grew up referring to the Holy Spirit it seems more natural to me. However, it also goes against the general aesthetic we have of keeping the original words and only modernizing the spelling. I'm not trying to make a slippery slope argument... but I think starting to change words like this might _actually_ be one.

So at this point I'd vote for keeping the original "Holy Ghost" and taking that search/replace out of the set. But I don't feel strongly either way - maybe 55/45. Anyone else have thoughts, like @physicswizkid  or @hudapaba?

**Comment by hudapaba** [comment]
I would prefer leaving "Holy Ghost", but not because I think it's better theologically. I just enjoy the reminder of the historicity of the faith.

**Comment by lukewil** [comment]
Agreed - I just looked into the file with searches/replaces, and it is **not** switching from `Holy Spirit` to `Holy Ghost.`  The texts with it changed either must have been early editions when I was modernizing more, or possibly it was a change from CCEL if the text was from there originally.

I'm going to go ahead and close this issue though, since it's unanimous. 

**FINAL ANSWER:** Use whichever glorious Name the original used!
